import RecipeForm from "@/app/components/CreateRecipe/ReciprForm";

export const metadata = {
  title: "Edit Recipe",
  description: "Generated by create next app",
};

export default function EditMyRecipe() {
  return (
    <>
      <RecipeForm />
    </>
  );
}
