// httpリクエストがエラーの場合のエラーハンドリングの検証。のちほど削除します。

export const metadata = {
  title: "Handling",
  description: "Generated by create next app",
};

export default async function ChefRecipes() {
  const res = await fetch("https://maps.googleapis.com/maps/api/geocode/json");
  const data = await res.json();

  //   サーバーログに出力される
  // console.log(data);

  if (!res.ok) {
    throw new Error(` ${res.status}:${data.error_message}`);
  }

  return (
    <>
      <h2 className="text-4xl font-bold">Handling</h2>
      <ul>
        {data.map((post: any) => (
          <li key={post.id}>
            <p>{post.title}</p>
          </li>
        ))}
      </ul>
    </>
  );
}
