import SideBar from "../components/NavBar/SideBar";
import SearchInput2 from "../components/Parts/SearchInput2";
import AllRecipes from "../components/Recipes/AllRecipes";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function Recipes() {
  return (
    <main className="pb-[58px] md:pb-[8px] md:max-w-[480px] md:mx-auto md:w-[480px] md:h-auto md:border-x-border md:border-x-[1px] md:relative">
      <SearchInput2 />
      <AllRecipes />
      <SideBar />
    </main>
  );
}
