import Link from "next/link";
import Image from "next/image";
import { LoginScreen } from "../components/Auth/LoginScreen";
import { getServerSession } from "next-auth";
import FavoriteChefs from "../components/Favorite/FavoriteChefs";
import NewRecipes from "../components/Favorite/NewRecipes";
import FavoriteRecipes from "../components/Favorite/FavoriteRecipes";
import { UserCircle, Menu } from "tabler-icons-react";
import { nextAuthOptions } from "@/server/utils/next-auth";

export const metadata = {
  title: "Favorite",
  description: "Generated by create next app",
};

async function FavoriteContents() {
  return (
    <>
      {/* シェフ */}
      <FavoriteChefs />

      {/* 新着レシピ */}
      <NewRecipes />

      {/* お気に入りレシピ */}
      <FavoriteRecipes />
    </>
  );
}

export default async function Favorite() {
  const session = await getServerSession(nextAuthOptions);
  const userId = await session?.user.userId;

  return (
    <>
      {/* ヘッダー */}
      <div className="flex justify-between px-[15px] border-b-[1px] border-border text-center text-title font-bold text-[20px] py-[12px] items-center">
        {session && (
          <Link href="/settings">
            <Menu size={24} strokeWidth={1.5} color={"black"} />
          </Link>
        )}
        <h1 className="flex-grow text-center">お気に入り</h1>
        {session && (
          <Link href={`/mypage/${userId}/recipes`}>
            <UserCircle size={24} strokeWidth={1.5} color={"black"} />
          </Link>
        )}
      </div>

      {session === null ? (
        <div>
          <Image
            src="/images/girlBakingCookie.png"
            width="200"
            height="200"
            alt="クッキーを焼く女の子"
            className="mx-auto"
            priority={true}
          />
          <LoginScreen />
        </div>
      ) : (
        <FavoriteContents />
      )}
    </>
  );
}
