import Link from "next/link";
import Image from "next/image";
import { LoginScreen } from "../components/Auth/LoginScreen";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Favorite",
  description: "Generated by create next app",
};

const chefCard = (
  <li className="w-[68px] relative overflow-hidden flex-none">
    <Link href="/recipe/1/steps">
      <Image src="/images/favChef.png" alt="シェフの写真" width={68} height={68} />
      <p className="text-[12px] mt-[4px] text-center">山田シェフ</p>
    </Link>
  </li>
);

const recipeCard = (
  <li className="w-[calc(50%_-_6px)] h-auto relative">
    <Link href="/">
      <Image
        src="/images/top/recipes/recipe1.png"
        alt="シェフの写真"
        width={173}
        height={173}
        style={{ width: "100%", height: "auto" }}
      />
      <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
        <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
          <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
        </span>
        1,234
      </div>
      <p className="text-title font-bold mt-[8px] text-[12px]">トマトとルッコラのマルゲリータピザに合うホワイト...</p>
      <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
    </Link>
  </li>
);

export default async function Favorite() {
  const session = await getServerSession();

  return (
    <>
      {/* ヘッダー */}
      <div className="px-[15px] border-b-[1px] border-border text-center text-title font-bold text-[20px] py-[12px]">
        <h1>お気に入り</h1>
      </div>

      {session === null ? (
        <LoginScreen />
      ) : (
        <>
          {/* シェフ */}
          <section className=" pt-[20px] overflow-hidden">
            <h2 className="text-title font-bold text-[20px] px-[16px]">シェフ</h2>
            <ul className="flex gap-x-[16px] mt-[12px] w-screen  overflow-x-scroll md:w-full pl-[16px]">
              {chefCard}
              {chefCard}
              {chefCard}
              {chefCard}
              {chefCard}
              {chefCard}
            </ul>
          </section>

          {/* レシピ */}
          <section className="px-[16px] py-[48px]">
            <div className="flex center justify-between">
              <h2 className="text-[20px] font-bold text-title">レシピ</h2>
              <Link href="/my-recipe/create" className="font-bold text-[16px]">
                マイレシピを作成
              </Link>
            </div>
            <ul className="flex justify-between gap-y-[16px] gap-x-[12px] flex-wrap mt-[10px]">
              {recipeCard}
              {recipeCard}
              {recipeCard}
              {recipeCard}
              {recipeCard}
              {recipeCard}
              {recipeCard}
              {recipeCard}
            </ul>
          </section>
        </>
      )}
    </>
  );
}
