import ChefHero from "@/app/components/Chef/ChefHero";
import { ChefsRecipeCard } from "@/app/components/Chef/ChefsRecipeCard";
import { trpcCaller } from "@/server/trpc/router";

export const metadata = {
  title: "Chef",
  description: "Generated by create next app",
};

export default async function HotRecipes({ params }: { params: { id: string } }) {
  const chefId = params.id;
  const chef = await trpcCaller.chef({ chefId });

  return (
    <>
      <ChefHero page="hotrecipes" chef={chef} />

      {/* レシピ */}
      <section className="pt-[20px] px-[15px] pb-[48px]">
        <ul className="flex justify-between gap-y-[16px] gap-x-[12px] flex-wrap">
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
        </ul>
      </section>
    </>
  );
}
