import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ChevronRight } from "tabler-icons-react";

export const metadata = {
  title: "Terms and conditions",
  description: "Generated by create next app",
};

export default async function Terms() {
  return (
    <>
      <div className="flex items-center gap-4 px-[15px] py-[12px] border-b-[1px] border-border text-center text-title font-bold text-[20px]">
        <Link href="/favorite">
          <ArrowLeft />
        </Link>
        <h1>利用規約</h1>
      </div>
      <div>
        <p className="font-bold px-4">第一項</p>
        <h2>第一項</h2>
      </div>
      <div>
        <p className="font-bold px-4">第二項</p>
      </div>
    </>
  );
}
