export const metadata = {
  title: "Terms and conditions",
  description: "Generated by create next app",
};

export default async function Terms() {
  return (
    <>
      <h1>規約画面テスト</h1>
    </>
  );
}
