import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ChevronRight } from "tabler-icons-react";

export const metadata = {
  title: "Terms and conditions",
  description: "Generated by create next app",
};

export default async function Terms() {
  return (
    <>
      <div className="flex items-center gap-4 px-[15px] py-[12px] border-b-[1px] border-border text-center text-title font-bold text-[20px]">
        <Link href="/favorite">
          <ArrowLeft />
        </Link>
        <h1>利用規約</h1>
      </div>
      <div>
        <h2 className="font-bold px-4 mt-4">第一項</h2>
        <p className="px-4 mt-4 mb-4">
          吾輩は猫である。名前はまだ無い。どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。
          <br></br>
          &nbsp;<br></br>
          吾輩は猫である。名前はまだ無い。どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。
        </p>
      </div>
      <div>
        <h2 className="font-bold px-4 mt-4">第二項</h2>
        <p className="px-4 mt-4 mb-4">
          吾輩は猫である。名前はまだ無い。どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。
          <br></br>
          &nbsp;<br></br>
          吾輩は猫である。名前はまだ無い。どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。
        </p>
      </div>
    </>
  );
}
