import RecipeForm from "../../components/CreateRecipe/ReciprForm";

export const metadata = {
  title: "Create Recipe",
  description: "Generated by create next app",
};

export default function CreateMyRecipe() {
  return (
    <>
      <RecipeForm />
    </>
  );
}
