import { getServerSession } from "next-auth";
import { nextAuthOptions } from "@/server/utils/next-auth";
import { RecipeForm } from "@/app/components/CreateRecipe/ReciprForm";

export const metadata = {
  title: "Create Recipe",
  description: "Generated by create next app",
};

export default async function CreateMyRecipe() {
  const session = await getServerSession(nextAuthOptions);
  console.log(session);
  return (
    <>
      <RecipeForm userId={session?.user.userId} />
    </>
  );
}
