import MyRecipeHero from "@/app/components/MyRecipe/MyRecipeHero";
import CopyClipboard from "@/app/components/Parts/CopyClipboard";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default async function MyRecipeSteps({ params }: { params: { id: string } }) {
  const recipe = {
    id: "1",
    name: "トマトとルッコラのマルゲリータピザに合うホワイトソース",
    description: "トマトとルッコラのマルゲリータピザに合うホワイトソースの作り方を紹介します。",
    _count: {
      favorites: 1,
    },
  };

  return (
    <>
      <MyRecipeHero page="steps" recipe={recipe} />

      {/* 作り方 */}
      <section className="pb-[48px]">
        <ul>
          <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
            <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
              1
            </span>
            <p className="text-title text-[14px]">
              用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
            </p>
          </li>
          <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
            <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
              1
            </span>
            <p className="text-title text-[14px]">
              用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
            </p>
          </li>
          <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
            <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
              1
            </span>
            <p className="text-title text-[14px]">
              用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
            </p>
          </li>
        </ul>

        <CopyClipboard text="コピーする" />
      </section>
    </>
  );
}
