import CopyClipboard from "@/app/components/Parts/CopyClipboard";
import RecipeHero from "@/app/components/Recipe/RecipeHero";
import { trpcCaller } from "@/server/trpc/router";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default async function RecipeIngredients({ params }: { params: { id: string } }) {
  const recipeId = params.id;
  const recipe = await trpcCaller.recipe({ recipeId });
  const text = recipe.ingredients
    .map((ingredient) => {
      return `${ingredient.title} ${ingredient.description}`;
    })
    .join("\n");

  return (
    <>
      <RecipeHero page="steps" recipe={{ ...recipe, chef: recipe.chefRecipe?.chef }} />

      {/* 材料 */}
      <section className="pb-[48px]">
        <div className="flex justify-between pt-[20px] pb-[10.5px] px-[15px] items-center border-b-[1px] border-border font-bold">
          <p className="text-title text-[20px] ">{recipe.yields}人前</p>
          <button className="relative pl-[20px] stroke-[#908E96] hover:stroke-primary hover:text-primary">
            <svg
              width="18"
              height="18"
              viewBox="0 0 18 18"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="stroke-current absolute left-0 top-1/2 -translate-y-1/2 "
            >
              <path
                d="M3 14.25C3 14.6478 3.15804 15.0294 3.43934 15.3107C3.72064 15.592 4.10218 15.75 4.5 15.75C4.89782 15.75 5.27936 15.592 5.56066 15.3107C5.84196 15.0294 6 14.6478 6 14.25C6 13.8522 5.84196 13.4706 5.56066 13.1893C5.27936 12.908 4.89782 12.75 4.5 12.75C4.10218 12.75 3.72064 12.908 3.43934 13.1893C3.15804 13.4706 3 13.8522 3 14.25Z"
                // stroke="#908E96"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M11.25 14.25C11.25 14.6478 11.408 15.0294 11.6893 15.3107C11.9706 15.592 12.3522 15.75 12.75 15.75C13.1478 15.75 13.5294 15.592 13.8107 15.3107C14.092 15.0294 14.25 14.6478 14.25 14.25C14.25 13.8522 14.092 13.4706 13.8107 13.1893C13.5294 12.908 13.1478 12.75 12.75 12.75C12.3522 12.75 11.9706 12.908 11.6893 13.1893C11.408 13.4706 11.25 13.8522 11.25 14.25Z"
                // stroke="#908E96"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M12.75 12.75H4.5V2.25H3"
                // stroke="#908E96"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M4.50003 3.75L9.00003 4.07175M14.3535 9.0015L14.2463 9.7515H4.49628"
                // stroke="#908E96"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M11.25 4.5H15.75M13.5 2.25V6.75"
                // stroke="#908E96"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            まとめてお買い物に追加
          </button>
        </div>

        <ul>
          {recipe.ingredients.map((ingredient) => (
            <li className="relative border-b-[1px] border-border px-[16px] py-[8px]" key={ingredient.id}>
              <p className="text-title text-[14px]">{ingredient.title}</p>
              <p className="text-[10px] mt-[4px]">{ingredient.description}</p>
              <span className="absolute top-1/2 -translate-y-1/2 right-[16px] pl-[20px] stroke-[#908E96] hover:stroke-primary hover:text-primary">
                <svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <g clipPath="url(#clip0_3478_253)">
                    <path
                      d="M3.33331 16.3334C3.33331 16.7754 3.50891 17.1994 3.82147 17.5119C4.13403 17.8245 4.55795 18.0001 4.99998 18.0001C5.44201 18.0001 5.86593 17.8245 6.17849 17.5119C6.49105 17.1994 6.66665 16.7754 6.66665 16.3334C6.66665 15.8914 6.49105 15.4675 6.17849 15.1549C5.86593 14.8423 5.44201 14.6667 4.99998 14.6667C4.55795 14.6667 4.13403 14.8423 3.82147 15.1549C3.50891 15.4675 3.33331 15.8914 3.33331 16.3334Z"
                      // stroke="#6F6E77"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M12.5 16.3334C12.5 16.7754 12.6756 17.1994 12.9882 17.5119C13.3007 17.8245 13.7246 18.0001 14.1667 18.0001C14.6087 18.0001 15.0326 17.8245 15.3452 17.5119C15.6577 17.1994 15.8333 16.7754 15.8333 16.3334C15.8333 15.8914 15.6577 15.4675 15.3452 15.1549C15.0326 14.8423 14.6087 14.6667 14.1667 14.6667C13.7246 14.6667 13.3007 14.8423 12.9882 15.1549C12.6756 15.4675 12.5 15.8914 12.5 16.3334Z"
                      // stroke="#6F6E77"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M14.1666 14.6667H4.99998V3H3.33331"
                      // stroke="#6F6E77"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M5.00002 4.66675L10 5.02425M15.9484 10.5017L15.8292 11.3351H4.99585"
                      // stroke="#6F6E77"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M12.5 5.5H17.5M15 3V8"
                      // stroke="#6F6E77"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </g>
                  <defs>
                    <clipPath id="clip0_3478_253">
                      <rect width="20" height="20" fill="white" transform="translate(0 0.5)" />
                    </clipPath>
                  </defs>
                </svg>
              </span>
            </li>
          ))}
        </ul>

        <CopyClipboard text={text} />
      </section>
    </>
  );
}
