import CopyClipboard from "@/app/components/Parts/CopyClipboard";
import RecipeHero from "@/app/components/Recipe/RecipeHero";
import { trpcClient } from "@/app/utils/trpc";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default async function RecipeSteps({ params }: { params: { id: string } }) {
  const recipeId = params.id;
  const recipe = await trpcClient.recipe.query({ recipeId });

  const text = recipe.processes
    .map((process) => {
      return `${process.order} ${process.title} ${process.description}`;
    })
    .join("\n");

  return (
    <>
      <RecipeHero page="steps" recipe={{ ...recipe, chef: recipe.chefRecipe?.chef }} />

      {/* 作り方 */}
      <section className="pb-[48px]">
        <ul>
          {recipe.processes.map((process) => (
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative" key={process.id}>
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                {process.order}
              </span>
              <p className="text-title text-[14px]">{process.title}</p>
              <p className="mt-[4px] text-[10px]">{process.description}</p>
            </li>
          ))}
        </ul>

        <CopyClipboard text={text} />
      </section>
    </>
  );
}
