import Image from "next/image";
import SideBar from "@/app/components/NavBar/SideBar";
import Link from "next/link";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function RecipeSteps() {
  return (
    <main className="pb-[58px] md:pb-[8px] md:max-w-[480px] md:mx-auto md:w-[480px] md:h-auto md:border-x-border md:border-x-[1px] md:relative">
      <div>
        {/* Hero */}
        <div className="relative">
          <Image
            src="/images/RecipeHero.png"
            alt="Picture of the recipe"
            width={390}
            height={390}
            style={{ width: "100%", height: "auto" }}
          />

          <button className="stroke-white hover:stroke-primary absolute top-[20px] left-[20px]">
            <svg
              width="32"
              height="32"
              viewBox="0 0 32 32"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M25.3333 16H6.66666"
                // stroke="white"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <path
                d="M16 25.3333L6.66666 16L16 6.66666"
                // stroke="white"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </button>
          <button className="absolute -bottom-[2px] right-[18px]">
            <svg
              width="60"
              height="60"
              viewBox="0 0 60 60"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="30" cy="30" r="30" fill="#E54D2E" />
              <path
                d="M42.63 20.87C41.8775 20.1149 40.9833 19.5157 39.9987 19.1069C39.0142 18.6981 37.9586 18.4876 36.8925 18.4876C35.8264 18.4876 34.7708 18.6981 33.7863 19.1069C32.8017 19.5157 31.9075 20.1149 31.155 20.87L30 22.04L28.845 20.87C28.0925 20.1149 27.1983 19.5157 26.2137 19.1069C25.2292 18.6981 24.1736 18.4876 23.1075 18.4876C22.0414 18.4876 20.9858 18.6981 20.0013 19.1069C19.0167 19.5157 18.1225 20.1149 17.37 20.87C14.19 24.05 13.995 29.42 18 33.5L30 45.5L42 33.5C46.005 29.42 45.81 24.05 42.63 20.87Z"
                stroke="white"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </button>
        </div>

        {/* Recipe詳細 */}
        <div className="px-[16px] pt-[16px] pb-[18.17px]">
          <h1 className="font-bold text-title text-[27px]">グラタン</h1>
          <p className="mt-[16px] text-title text-[16px] leading-snug ">
            はじめてでも失敗なく作れるような、鶏肉や玉ねぎを具とした基本的なマカロニグラタンのレシピです。
            <br></br>
            ソースと具材炒めを別器具で行うレシピも多いですが、グラタンの具を炒めたフライパンの中で、そのままホワイトソースを仕上げる手軽な作り方にしています。ぜひお試しください。
          </p>
          <p className="pt-[14.17px] text-[16px] leading-snug">
            <span className="text-title font-bold">456</span> お気に入り
          </p>
        </div>

        {/* ナビゲーション */}
        <nav className="border-b-[1px] border-border">
          <ul className="flex text-title">
            <li className="w-1/2 text-center text-[16px] font-bold border-b-[2px]">
              <Link href="/recipes/1/steps" className="block py-[10px]">
                作り方
              </Link>
            </li>
            <li className="w-1/2 text-center text-[16px] ">
              <Link href="/recipes/1/ingredients" className="block py-[10px]">
                材料
              </Link>
            </li>
          </ul>
        </nav>

        {/* 材料 */}
        <section className="pb-[48px]">
          <ul>
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                1
              </span>
              <p className="text-title text-[14px]">
                用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
              </p>
              <p className="mt-[4px] text-[10px]">
                ※椎茸はなしでも作れますし、しめじやマッシュルームなどでも。きのこ系が入っていた方が食感と香りがよいので、ぜひ入れて作ってみてください。鶏肉等の代用については下記補足に
              </p>
            </li>
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                1
              </span>
              <p className="text-title text-[14px]">
                用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
              </p>
              <p className="mt-[4px] text-[10px]">
                ※椎茸はなしでも作れますし、しめじやマッシュルームなどでも。きのこ系が入っていた方が食感と香りがよいので、ぜひ入れて作ってみてください。鶏肉等の代用については下記補足に
              </p>
            </li>
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                1
              </span>
              <p className="text-title text-[14px]">
                用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
              </p>
              <p className="mt-[4px] text-[10px]">
                ※椎茸はなしでも作れますし、しめじやマッシュルームなどでも。きのこ系が入っていた方が食感と香りがよいので、ぜひ入れて作ってみてください。鶏肉等の代用については下記補足に
              </p>
            </li>
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                1
              </span>
              <p className="text-title text-[14px]">
                用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
              </p>
              <p className="mt-[4px] text-[10px]">
                ※椎茸はなしでも作れますし、しめじやマッシュルームなどでも。きのこ系が入っていた方が食感と香りがよいので、ぜひ入れて作ってみてください。鶏肉等の代用については下記補足に
              </p>
            </li>
            <li className="py-[8px] pr-[16px] pl-[42px] border-b-[1px] border-border relative">
              <span className="absolute top-[8px] left-[16px] w-[18px] h-[18px] text-white text-[12px] rounded-full bg-primary text-center leading-[18px] ">
                1
              </span>
              <p className="text-title text-[14px]">
                用意するメインの材料は、マカロニ、牛乳、鶏もも肉、玉ねぎ、椎茸で、バター、小麦粉、塩、こしょうも使用します。
              </p>
              <p className="mt-[4px] text-[10px]">
                ※椎茸はなしでも作れますし、しめじやマッシュルームなどでも。きのこ系が入っていた方が食感と香りがよいので、ぜひ入れて作ってみてください。鶏肉等の代用については下記補足に
              </p>
            </li>
          </ul>
          <button className="mt-[8.5px] pl-[18px] float-right pr-[16px] text-[12px] text-[#0066DB] relative">
            <span className="absolute left-0 top-1/2 -translate-y-1/2">
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <g clip-path="url(#clip0_3478_1001)">
                  <path
                    d="M5.33331 6.66659C5.33331 6.31296 5.47379 5.97383 5.72384 5.72378C5.97389 5.47373 6.31302 5.33325 6.66665 5.33325H12C12.3536 5.33325 12.6927 5.47373 12.9428 5.72378C13.1928 5.97383 13.3333 6.31296 13.3333 6.66659V11.9999C13.3333 12.3535 13.1928 12.6927 12.9428 12.9427C12.6927 13.1928 12.3536 13.3333 12 13.3333H6.66665C6.31302 13.3333 5.97389 13.1928 5.72384 12.9427C5.47379 12.6927 5.33331 12.3535 5.33331 11.9999V6.66659Z"
                    stroke="#006ADC"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M10.6667 5.33341V4.00008C10.6667 3.64646 10.5262 3.30732 10.2762 3.05727C10.0261 2.80722 9.68698 2.66675 9.33335 2.66675H4.00002C3.6464 2.66675 3.30726 2.80722 3.05721 3.05727C2.80716 3.30732 2.66669 3.64646 2.66669 4.00008V9.33341C2.66669 9.68704 2.80716 10.0262 3.05721 10.2762C3.30726 10.5263 3.6464 10.6667 4.00002 10.6667H5.33335"
                    stroke="#006ADC"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_3478_1001">
                    <rect width="16" height="16" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </span>
            コピーする
          </button>
        </section>
      </div>
      <SideBar />
    </main>
  );
}
