import AllChefs from "@/app/components/Chefs/AllChefs";
import SearchInput2 from "@/app/components/Parts/SearchInput2";
import SearchNav from "@/app/components/Parts/SearchNav";

export const metadata = {
  title: "Chefs",
  description: "Generated by create next app",
};

export default function Chefs({ searchParams }: { searchParams: { [key: string]: string | string[] | undefined } }) {
  return (
    <>
      <SearchInput2 page="chef" searchParams={searchParams} />
      <SearchNav page="chef" searchParams={searchParams} />
      <AllChefs searchParams={searchParams} />
    </>
  );
}
