import AllChefs from "@/app/components/Chefs/AllChefs";
import SearchInput2 from "@/app/components/Parts/SearchInput2";
import SearchNav from "@/app/components/Parts/SearchNav";
import { trpcCaller } from "@/server/trpc/router";

export const metadata = {
  title: "Chefs",
  description: "Generated by create next app",
};

export default async function Chefs({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const chefs = await trpcCaller.chefs({});

  return (
    <>
      <SearchInput2 page="chef" searchParams={searchParams} />
      <SearchNav page="chef" searchParams={searchParams} />
      <AllChefs searchParams={searchParams} chefs={chefs} />
    </>
  );
}
