import SearchInput2 from "@/app/components/Parts/SearchInput2";
import SearchNav from "@/app/components/Parts/SearchNav";
import AllRecipes from "@/app/components/Recipes/AllRecipes";
import Link from "next/link";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function Recipes() {
  return (
    <>
      <SearchInput2 />
      <SearchNav page="recipes" />
      <AllRecipes />
    </>
  );
}
