import SearchInput2 from "@/app/components/Parts/SearchInput2";
import SearchNav from "@/app/components/Parts/SearchNav";
import AllRecipes from "@/app/components/Recipes/AllRecipes";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function Recipes({ searchParams }: { searchParams: { [key: string]: string | string[] | undefined } }) {
  return (
    <>
      <SearchInput2 page="recipe" searchParams={searchParams} />
      <SearchNav page="recipe" searchParams={searchParams} />

      <AllRecipes searchParams={searchParams} />
    </>
  );
}
