import Link from "next/link";

export const metadata = {
    title: "My Recipe Drafts",
    description: "Generated by create next app",
};

export default function MyRecipeDraft() {

    return (
        <>
            {/* ヘッダー */}
            <div className="px-[15px] border-b-[1px] border-border text-title font-bold text-[20px] py-[12px]  flex items-center gap-x-[16px]">
                <Link href="/my-recipe/create">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clipPath="url(#clip0_393_1908)">
                            <path d="M5 12H19" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path d="M5 12L11 18" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path d="M5 12L11 6" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </g>
                        <defs>
                            <clipPath id="clip0_393_1908">
                                <rect width="24" height="24" fill="white" />
                            </clipPath>
                        </defs>
                    </svg>
                </Link>

                <h1 className="text-[#020010]">下書き</h1>
            </div>

            <section className=" pb-[24px] ">
                <ul className="bg-white">
                    <li className=" text-[14px] border-border border-b-[1px] leading-[18px]">
                        <Link className="py-[15.5px] px-[16px] block" href="/recipe/1/edit">
                            <p className="text-title text-[14px]">グラタン</p>
                            <p className="mt-[6px] text-[12px] leading-[12px]">作成日時: 2023年4月12日</p>
                        </Link>
                    </li>
                    <li className=" text-[14px] border-border border-b-[1px] leading-[18px]">
                        <Link className="py-[15.5px] px-[16px] block" href="/recipe/1/edit">
                            <p className="text-title text-[14px]">グラタン</p>
                            <p className="mt-[6px] text-[12px] leading-[12px]">作成日時: 2023年4月12日</p>
                        </Link>
                    </li>
                </ul>
            </section>
        </>
    );
}
