import { Dialog } from "@/app/components/Drafts/Dialog";
import { ArrowLeft } from "tabler-icons-react";
import Link from "next/link";

export const metadata = {
  title: "My Recipe Drafts",
  description: "Generated by create next app",
};

// APIから取得する予定
const draftsArray = [
  {
    id: 1,
    title: "グラタン",
    createdDate: "2023年4月12日",
  },
  {
    id: 2,
    title: "レシピ名未記載",
    createdDate: "2023年4月1日",
  },
];

export default function MyRecipeDraft() {
  return (
    <>
      {/* ヘッダー */}
      <div className="px-[15px] border-b-[1px] border-border text-title font-bold text-[20px] py-[12px]  flex items-center gap-x-[16px]">
        <Link href="/my-recipe/create">
          <ArrowLeft size={24} strokeWidth={1.5} color={"#1A1523"} />
        </Link>

        <h1 className="text-[#020010]">下書き</h1>
      </div>

      <section className="pb-[24px] ">
        <ul className="bg-white">
          {draftsArray.map((draft) => (
            <li key={draft.id} className="text-[14px] border-border border-b-[1px] leading-[18px] relative">
              <Link className="py-[15.5px] px-[16px] block mr-[56px]" href="/recipe/1/edit">
                <p className="text-title text-[14px]">{draft.title}</p>
                <p className="mt-[6px] text-[12px] leading-[12px]">作成日時: {draft.createdDate}</p>
              </Link>
              <Dialog draftTitle={draft.title} />
            </li>
          ))}
        </ul>
      </section>
    </>
  );
}
