import { trpcClient } from "@/app/utils/trpc";
import Image from "next/image";
import Link from "next/link";
import { ChefNavigation } from "../ChefNavigation";
import { ChefsRecipeCard } from "@/app/components/Chef/ChefsRecipeCard";

export const metadata = {
  title: "Chef",
  description: "Generated by create next app",
};

export default async function ChefRecipes({ params }: { params: { id: string } }) {
  const chefId = params.id;
  const chef = await trpcClient.chef.query({ chefId });

  return (
    <>
      <ChefNavigation chefId={chef.id} page="recipes" />
      <section className="pt-[20px] px-[15px] pb-[48px]">
        {chef?.recipes?.length === 0 ? (
          <p className="text-title">レシピがまだありません！</p>
        ) : (
          <ul className="flex justify-between gap-y-[16px] gap-x-[12px] flex-wrap">
            {chef.recipes.map((recipe) => (
              <ChefsRecipeCard key={recipe.id} recipe={recipe} />
            ))}
          </ul>
        )}
      </section>
    </>
  );
}
