import ChefHero from "@/app/components/Chef/ChefHero";
import { ChefsRecipeCard } from "@/app/components/Chef/ChefsRecipeCard";
import { trpcClient } from "@/app/utils/trpc";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Chef",
  description: "Generated by create next app",
};

export default async function ChefRecipes({ params }: { params: { id: string } }) {
  const chefId = params.id;
  const chef = await trpcClient.chef.query({ chefId });

  return (
    <>
      <ChefHero page="recipes" chef={chef} />

      {/* レシピ */}
      <section className="pt-[20px] px-[15px] pb-[48px]">
        <ul className="flex justify-between gap-y-[16px] gap-x-[12px] flex-wrap">
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
          <ChefsRecipeCard />
        </ul>
      </section>
    </>
  );
}
