import ChefHero from "@/app/components/Chef/ChefHero";
import { trpcClient } from "@/app/utils/trpc";
import { trpcCaller } from "@/server/trpc/router";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Chef",
  description: "Generated by create next app",
};

export default async function ChefRecipes({ params }: { params: { id: string } }) {
  const chefId = params.id;
  const chef = await trpcCaller.chef({ chefId });

  return (
    <>
      <ChefHero page="recipes" chef={chef} />

      {/* レシピ */}
      <section className="pt-[20px] px-[15px] pb-[48px]">
        <p className="font-bold text-title text-[20px] mb-[10px]">123件</p>
        <ul className="flex justify-between gap-y-[16px] gap-x-[12px] flex-wrap">
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
          <li className="w-[calc(50%_-_6px)] h-auto relative">
            <Link href="/">
              <Image
                src="/images/top/recipes/recipe1.png"
                alt="シェフの写真"
                width={173}
                height={173}
                style={{ width: "100%", height: "auto" }}
              />
              <div className="rounded-[16px] absolute top-[8px] right-[8px] py-[8px] pr-[8px] pl-[25px] text-white text-[15px] leading-none bg-[#040013]/[.48]">
                <span className="absolute top-1/2 left-[8px] -translate-y-1/2 w-[14px] h-[14px] mt-[1.3px]">
                  <Image src="/images/top/recipes/favIcon.png" width={14} height={14} alt="vector icon" />
                </span>
                1,234
              </div>
              <p className="text-title font-bold mt-[8px] text-[12px]">
                トマトとルッコラのマルゲリータピザに合うホワイト...
              </p>
              <p className="text-[10px] mt-[4px]">ウルトラハイパー超すごいしまぶ...</p>
            </Link>
          </li>
        </ul>
      </section>
    </>
  );
}
